import SwiftUI
import Foundation

// MARK: - Design Tokens（⚠️ GENERATED by scripts/gen-design-tokens.py — 勿手改；改 token 请改 design-tokens.json 后重跑生成器）
//
// SSOT: shared/src/commonMain/resources/design-tokens.json
// 所有新增 UI 必须引用这些常量，禁止硬编码尺寸/颜色/圆角。
// 完整提取方法学/漂移记录/内容色板见 docs/03-TECHNICAL-SPECS/DESIGN_TOKENS_SPEC.md。

// MARK: - Spacing

enum Spacing {
    static let xs: CGFloat = 4
    static let sm: CGFloat = 8
    static let md: CGFloat = 12
    static let lg: CGFloat = 16
    static let xl: CGFloat = 24
    static let xxl: CGFloat = 32
}

// MARK: - Radius

enum AppRadius {
    static let panel: CGFloat = 12
    static let lg: CGFloat = 16
    static let card: CGFloat = 8
    static let button: CGFloat = 10
    static let small: CGFloat = 8
    static let thumbnail: CGFloat = 2
}

enum AppShapes {
    static let panel = RoundedRectangle(cornerRadius: AppRadius.panel, style: .continuous)
    static let lg = RoundedRectangle(cornerRadius: AppRadius.lg, style: .continuous)
    static let card = RoundedRectangle(cornerRadius: AppRadius.card, style: .continuous)
    static let button = RoundedRectangle(cornerRadius: AppRadius.button, style: .continuous)
    static let small = RoundedRectangle(cornerRadius: AppRadius.small, style: .continuous)
    static let thumbnail = RoundedRectangle(cornerRadius: AppRadius.thumbnail, style: .continuous)
}

// MARK: - Icon Sizes

enum IconSize {
    static let sm: CGFloat = 18
    static let md: CGFloat = 22
    static let lg: CGFloat = 24
    static let xl: CGFloat = 32
    static let strokeWidth: CGFloat = 1.6
}

// MARK: - App Colors（不随主题切换的固定功能色）

enum AppColors {
    static let focusRing = Color(hex: "FF00E5FF")
    static let panelBackground = Color(hex: "CC000000")
    static let providerTagBg = Color(hex: "FF07C160")
    static let providerTagLabel = Color(hex: "FF067045")
    static let shutterRing = Color(hex: "FFE4E4E4")
    static let sliderThumb = Color.white
    static let vibrantGreen = Color(hex: "FF00E676")
    static let vibrantBlue = Color(hex: "FF2979FF")
    static let vibrantOrange = Color(hex: "FFFF9100")
    static let vibrantPink = Color(hex: "FFFF4081")
    static let vibrantPurple = Color(hex: "FF4F378B")
    static let vibrantAmber = Color(hex: "FFFFA000")
    static let iconOnVibrant = Color.white
    static let voiceButtonIcon = Color(hex: "FF888888")
    static let white = Color.white
    static let amber = Color(hex: "FFFFB020")
    static let lavender = Color(hex: "FFD0BCFF")
    static let mint = Color(hex: "FF8FD6C6")
    static let paperWarm = Color(hex: "FFEDE9E3")
    static let softBlue = Color(hex: "FF6BA6FF")
    static let tagChipLine = Color(hex: "FF46413A")
    static let tagCyan = Color(hex: "FF22D3EE")
    static let tagGreen = Color(hex: "FF4ADE80")
    static let tagPink = Color(hex: "FFFF7DB0")
    static let tagPurple = Color(hex: "FF9C8CFF")
}

// MARK: - Typography（M3 baseline 字号阶梯，仅 bodyLarge 为定制）

/// 字号角色。`font` 直接产出 SwiftUI Font；`lineHeight`/`letterSpacing` 供 `.lineSpacing`/`.tracking` 使用。
struct TypeStyle {
    let size: CGFloat
    let lineHeight: CGFloat
    let weight: Font.Weight
    let letterSpacing: CGFloat

    var font: Font { .system(size: size, weight: weight) }
}

enum AppTypography {
    static let displayLarge = TypeStyle(size: 57, lineHeight: 64, weight: .regular, letterSpacing: -0.25)
    static let displayMedium = TypeStyle(size: 45, lineHeight: 52, weight: .regular, letterSpacing: 0)
    static let displaySmall = TypeStyle(size: 36, lineHeight: 44, weight: .regular, letterSpacing: 0)
    static let headlineLarge = TypeStyle(size: 32, lineHeight: 40, weight: .regular, letterSpacing: 0)
    static let headlineMedium = TypeStyle(size: 28, lineHeight: 36, weight: .regular, letterSpacing: 0)
    static let headlineSmall = TypeStyle(size: 24, lineHeight: 32, weight: .regular, letterSpacing: 0)
    static let titleLarge = TypeStyle(size: 22, lineHeight: 28, weight: .regular, letterSpacing: 0)
    static let titleMedium = TypeStyle(size: 17, lineHeight: 24, weight: .medium, letterSpacing: 0.15)
    static let titleSmall = TypeStyle(size: 14, lineHeight: 20, weight: .medium, letterSpacing: 0.1)
    static let bodyLarge = TypeStyle(size: 16, lineHeight: 24, weight: .regular, letterSpacing: 0.5)
    static let bodyMedium = TypeStyle(size: 14, lineHeight: 20, weight: .regular, letterSpacing: 0.25)
    static let bodySmall = TypeStyle(size: 12, lineHeight: 16, weight: .regular, letterSpacing: 0.4)
    static let labelLarge = TypeStyle(size: 14, lineHeight: 20, weight: .medium, letterSpacing: 0.1)
    static let labelMedium = TypeStyle(size: 12, lineHeight: 16, weight: .medium, letterSpacing: 0.5)
    static let labelSmall = TypeStyle(size: 10, lineHeight: 16, weight: .medium, letterSpacing: 0.5)

    /// 内联字重覆盖（Android 在 M3 role 之上叠加：模型卡名 SemiBold、必备徽章 Bold 等）。
    enum WeightOverride {
        static let semibold: Font.Weight = .semibold
        static let bold: Font.Weight = .bold
    }
}

// MARK: - Color Scheme（M3 baseline，iOS 无动态取色，以此为语义色基准）

/// 一组随主题切换的语义色。Android 12+ 走 Material You 动态取色，iOS 无等价物，统一用此基准。
/// 已修正 Android 端两处 bug：ErrorLight alpha=00 透明、Dark tertiaryContainer 误指 TertiaryDark。
struct SchemeColors {
    let primary: Color
    let onPrimary: Color
    let primaryContainer: Color
    let onPrimaryContainer: Color
    let secondary: Color
    let onSecondary: Color
    let secondaryContainer: Color
    let onSecondaryContainer: Color
    let tertiary: Color
    let onTertiary: Color
    let tertiaryContainer: Color
    let onTertiaryContainer: Color
    let error: Color
    let onError: Color
    let errorContainer: Color
    let onErrorContainer: Color
    let background: Color
    let onBackground: Color
    let surface: Color
    let onSurface: Color
    let surfaceVariant: Color
    let onSurfaceVariant: Color
    let outline: Color
    let outlineVariant: Color
    let surfaceContainerLowest: Color
    let surfaceContainerLow: Color
    let surfaceContainer: Color
    let surfaceContainerHigh: Color
    let surfaceContainerHighest: Color
    let warmGrayIcon: Color
    let cell: Color
}

enum AppColorScheme {
    static let light = SchemeColors(
        primary: Color(hex: "FF07C160"),
        onPrimary: Color.white,
        primaryContainer: Color(hex: "FFD7F2E2"),
        onPrimaryContainer: Color(hex: "FF0A6B3F"),
        secondary: Color(hex: "FF888888"),
        onSecondary: Color.white,
        secondaryContainer: Color(hex: "FFF2F2F2"),
        onSecondaryContainer: Color(hex: "FF4D4D4D"),
        tertiary: Color(hex: "FF576B95"),
        onTertiary: Color.white,
        tertiaryContainer: Color(hex: "FFE9EDF5"),
        onTertiaryContainer: Color(hex: "FF3A4A6B"),
        error: Color(hex: "FFFA5151"),
        onError: Color.white,
        errorContainer: Color(hex: "FFFDEBEB"),
        onErrorContainer: Color(hex: "FF8F1F1F"),
        background: Color(hex: "FFEDEDED"),
        onBackground: Color(hex: "FF181818"),
        surface: Color(hex: "FFEDEDED"),
        onSurface: Color(hex: "FF181818"),
        surfaceVariant: Color(hex: "FFF2F2F2"),
        onSurfaceVariant: Color(hex: "FF888888"),
        outline: Color(hex: "FFB2B2B2"),
        outlineVariant: Color(hex: "FFE5E5E5"),
        surfaceContainerLowest: Color.white,
        surfaceContainerLow: Color(hex: "FFF7F7F7"),
        surfaceContainer: Color(hex: "FFF7F7F7"),
        surfaceContainerHigh: Color(hex: "FFEDEDED"),
        surfaceContainerHighest: Color(hex: "FFE5E5E5"),
        warmGrayIcon: Color(hex: "FF888888"),
        cell: Color.white
    )

    static let dark = SchemeColors(
        primary: Color(hex: "FF07C160"),
        onPrimary: Color.white,
        primaryContainer: Color(hex: "FF14562F"),
        onPrimaryContainer: Color(hex: "FFB7E9C9"),
        secondary: Color(hex: "FF7F7F7F"),
        onSecondary: Color.white,
        secondaryContainer: Color(hex: "FF2C2C2C"),
        onSecondaryContainer: Color(hex: "FFC9C9C9"),
        tertiary: Color(hex: "FF7D90B0"),
        onTertiary: Color.white,
        tertiaryContainer: Color(hex: "FF2A3346"),
        onTertiaryContainer: Color(hex: "FFC6D0E2"),
        error: Color(hex: "FFFA5151"),
        onError: Color.white,
        errorContainer: Color(hex: "FF3A1F1F"),
        onErrorContainer: Color(hex: "FFF9DEDC"),
        background: Color(hex: "FF111111"),
        onBackground: Color(hex: "FFD5D5D5"),
        surface: Color(hex: "FF111111"),
        onSurface: Color(hex: "FFD5D5D5"),
        surfaceVariant: Color(hex: "FF2C2C2C"),
        onSurfaceVariant: Color(hex: "FF7F7F7F"),
        outline: Color(hex: "FF5F5F5F"),
        outlineVariant: Color(hex: "FF2C2C2C"),
        surfaceContainerLowest: Color(hex: "FF0C0C0C"),
        surfaceContainerLow: Color(hex: "FF141414"),
        surfaceContainer: Color(hex: "FF1A1A1A"),
        surfaceContainerHigh: Color(hex: "FF222222"),
        surfaceContainerHighest: Color(hex: "FF2C2C2C"),
        warmGrayIcon: Color(hex: "FF7F7F7F"),
        cell: Color(hex: "FF1A1A1A")
    )
}

// MARK: - Scheme 解析（跨屏共享）

/// 按当前主题取 M3 语义色组。用法：`@Environment(\.colorScheme)` + `let s = appScheme(cs)`。
/// 各屏统一经此消费语义色，禁止硬编码 Color.white/opacity 近似（[PARITY] 契约色以 design-tokens.json 为准）。
func appScheme(_ cs: ColorScheme) -> SchemeColors {
    cs == .dark ? AppColorScheme.dark : AppColorScheme.light
}

// MARK: - Alpha（透明度语义阶梯）

enum AppAlpha {
    static let scrimModal: CGFloat = 0.7
    static let scrim: CGFloat = 0.55
    static let scrimDeep: CGFloat = 0.82
    static let surfaceTranslucent: CGFloat = 0.95
    static let fieldBackground: CGFloat = 0.7
    static let primaryTint: CGFloat = 0.12
    static let primaryTintSoft: CGFloat = 0.15
    static let primaryTintMedium: CGFloat = 0.2
    static let primaryTintStrong: CGFloat = 0.25
    static let emphasisHigh: CGFloat = 0.85
    static let emphasis: CGFloat = 0.8
    static let secondary: CGFloat = 0.6
    static let hint: CGFloat = 0.5
    static let placeholder: CGFloat = 0.4
    static let faint: CGFloat = 0.3
    static let ghost: CGFloat = 0.2
}

// MARK: - Status Color（语义状态色，不随主题）

enum StatusColor {
    static let success = Color(hex: "FF07C160")
    static let warning = Color(hex: "FFFF9800")
    static let warningAmber = Color(hex: "FFFFA000")
    static let error = Color(hex: "FFE53935")
    static let info = Color(hex: "FF576B95")
}

// MARK: - Motion（动效时长 + 缓动）

/// FastOutSlowInEasing 在 SwiftUI 的等价是 `.easeInOut`；禁用线性动画。
enum AppMotion {
    static let instantMs: Double = 80
    static let fastMs: Double = 150
    static let mediumMs: Double = 300
    static let slowMs: Double = 400
    static let blinkMs: Double = 500
    static let pulseMs: Double = 1200

    static let staggerMs: Double = 160
    static let searchDebounceMs: Double = 300
    static let shutterDebounceMs: Double = 500

    /// 相册预览进场（fade + scale，scale 0.2↔1.0）。
    static let galleryPreviewFadeMs: Double = 300
    static let galleryPreviewScaleMs: Double = 400
    static let galleryPreviewScaleFrom: CGFloat = 0.2
    static let galleryPreviewScaleTo: CGFloat = 1.0
}

// MARK: - Elevation（阴影/tonal 阶径）

enum AppElevation {
    static let none: CGFloat = 0
    static let low: CGFloat = 1
    static let medium: CGFloat = 2
    static let high: CGFloat = 4
    static let floating: CGFloat = 6
    static let sheet: CGFloat = 16
}

// MARK: - TopBar

enum TopBarTokens {
    static let height: CGFloat = 48
    static let buttonSize: CGFloat = 36
    static let iconSize: CGFloat = 22
    static let titleFontSize: CGFloat = 17
    static let titleFontWeight: Font.Weight = .semibold
    static let spacing: CGFloat = 8
    static let horizontalPadding: CGFloat = 8
}

// MARK: - Shutter

enum ShutterTokens {
    static let diameter: CGFloat = 76
    static let innerDiameter: CGFloat = 58
    static let recordingInnerDiameter: CGFloat = 28
    static let recordingInnerCornerRadius: CGFloat = 4
    static let ringWidth: CGFloat = 9
    static let pressDebounceMs: Double = 500
    static let flashAlpha: Double = 0.6
    static let flashFadeMs: Double = 80
}

// MARK: - Beauty Panel

enum BeautyPanelTokens {
    static let topCornerRadius: CGFloat = 24
    static let iconSize: CGFloat = 24
    static let sliderThumbSize: CGFloat = 18
    static let sliderTrackHeight: CGFloat = 6
    static let heightRatio: CGFloat = 0.4
    static let heightRatioMin: Double = 0.2
    static let heightRatioMax: Double = 0.75
}

// MARK: - App Slider（全 app 统一滑杆）

enum AppSliderTokens {
    static let trackHeight: CGFloat = 6
    static let thumbSize: CGFloat = 18
    static let thumbPressedScale: Double = 1.15
    static let thumbShadowElevation: CGFloat = 2
    static let thumbBorderWidth: CGFloat = 2
    static let thumbColor = Color.white
    static let inactiveTrackAlpha: Double = 0.12
    static let animDurationMs: Double = 150
}

// MARK: - Bottom Tab（悬浮胶囊导航）

enum BottomTabTokens {
    static let cornerRadius: CGFloat = 0
    static let tonalElevation: CGFloat = 3
    static let shadowElevation: CGFloat = 6
    static let containerPaddingH: CGFloat = 12
    static let containerPaddingV: CGFloat = 8
    static let itemPaddingH: CGFloat = 16
    static let itemPaddingVIconOnly: CGFloat = 10
    static let itemPaddingVWithLabel: CGFloat = 4
    static let iconSize: CGFloat = 24
    static let labelTopPadding: CGFloat = 2
}

// MARK: - Bottom Sheet（相机/编辑器共享面板外壳）

enum BottomSheetTokens {
    static let topCornerRadius: CGFloat = 24
    static let shadowElevation: CGFloat = 16
    static let surfaceAlpha: Double = 0.95
    static let borderWidth: CGFloat = 0.5
    static let borderColorAlpha: Double = 0.25
    static let gradientStops: [Color] = [
        Color.clear,
        Color.black.opacity(0.55),
        Color.black.opacity(0.82)
    ]
    static let handleWidth: CGFloat = 36
    static let handleHeight: CGFloat = 4
    static let handleColorAlpha: Double = 0.2
    static let contentPaddingH: CGFloat = 24
    static let contentPaddingV: CGFloat = 8
    static let contentSpacing: CGFloat = 12
}

// MARK: - Chip

enum ChipTokens {
    static let height: CGFloat = 36
    static let smallHeight: CGFloat = 32
    static let unselectedContainerAlpha: Double = 0.5
    static let selectedShadowElevation: CGFloat = 2
}

// MARK: - Badge

enum BadgeTokens {
    static let tagRadius: CGFloat = 6
    static let tagBackgroundAlpha: Double = 0.12
    static let tagDotSize: CGFloat = 6
    static let tagPaddingH: CGFloat = 8
    static let tagPaddingV: CGFloat = 3
    static let tagDotLabelGap: CGFloat = 4
    static let miniRadius: CGFloat = 4
    static let requiredRadius: CGFloat = 4
    static let requiredBg = Color(hex: "FFE53935")
    static let requiredLabelWeight: Font.Weight = .bold
    static let requiredLabelColor = Color.white
    static let listWidth: CGFloat = 44
    static let listHeight: CGFloat = 26
}

// MARK: - Camera（强制深色 overlay）

enum CameraTokens {
    static let focusRingDiameter: CGFloat = 100
    static let focusRingStrokeWidth: CGFloat = 3
    static let focusRingCornerRadius: CGFloat = 20
    static let focusRingCrossLength: CGFloat = 16
    static let controlButtonSize: CGFloat = 48
    static let controlButtonIconSize: CGFloat = 24
    static let controlButtonIdleAlpha: Double = 0.5
    static let modeTabFontSize: CGFloat = 13
    static let modeTabUnselectedAlpha: Double = 1.0
    static let voicePulseMs: Double = 1200
    static let voicePulseAlphaFrom: Double = 0.3
    static let voicePulseAlphaTo: Double = 1.0
    static let filterSelectorColumns: Int = 5
    static let filterSelectorHeight: CGFloat = 280
    static let filterSelectedScale: Double = 1.08
    static let filterSelectedBorderWidth: CGFloat = 2.5
    static let filterLabelFontSize: CGFloat = 10
    static let panelBackground = Color(hex: "B81C1A1F")
    static let cameraAccent = Color(hex: "FF07C160")
    static let cameraAccentOn = Color.white
    static let toolBarUnselectedBg = Color(hex: "00000000")
    static let inlineFilterPanelHeight: CGFloat = 200
    static let panelCornerRadius: CGFloat = 16
    static let panelMaxWidth: CGFloat = 420
    static let panelSideMargin: CGFloat = 28
    static let panelPaddingH: CGFloat = 16
    static let panelPaddingV: CGFloat = 10
    static let panelShadowElevation: CGFloat = 12
    static let chipHeight: CGFloat = 34
    static let chipPaddingH: CGFloat = 14
    static let chipSpacing: CGFloat = 10
    static let chipFontSize: CGFloat = 13
    static let wbChipPaddingH: CGFloat = 10
    static let wbChipSpacing: CGFloat = 8
    static let proSliderFontSize: CGFloat = 12
    static let topToolBarPaddingTop: CGFloat = 8
    static let topToolBarItemPaddingH: CGFloat = 10
    static let topToolBarItemPaddingV: CGFloat = 9
    static let topToolBarItemRadius: CGFloat = 10
    static let topToolBarSpacing: CGFloat = 6
    static let modeSwitcherSpacing: CGFloat = 24
    static let zoomBarSpacing: CGFloat = 12
    static let zoomCapsulePaddingH: CGFloat = 14
    static let zoomCapsuleHeight: CGFloat = 32
    static let zoomFontSize: CGFloat = 12
    static let zoomUnselectedBgAlpha: Double = 0.5
    static let bottomControlsPaddingBottom: CGFloat = 60
    static let controlLabelFontSize: CGFloat = 11
    static let albumThumbColor = Color(hex: "FF404040")
    static let albumPlaceholderIconColor = Color(hex: "FFE4E4E4")
    static let flipIconColor = Color(hex: "FF1C1B1F")
    static let wbChipFontSize: CGFloat = 12
    static let tealAccent = Color(hex: "FF0F766E")
    static let toolChipBg = Color(hex: "FF4A454F")
    static let toolBarSelectedBg: Color = CameraTokens.cameraAccent
}

// MARK: - Chat Bubble

enum ChatBubbleTokens {
    static let bubbleMaxWidth: CGFloat = 360
    static let imageMaxWidth: CGFloat = 240
    static let paddingH: CGFloat = 18
    static let paddingV: CGFloat = 14
    static let cornerRadius: CGFloat = 12
    static let tailCornerRadius: CGFloat = 4
    static let textSize: CGFloat = 16
    static let textLineHeight: CGFloat = 24
    static let inputCornerRadius: CGFloat = 8
    static let inputShadowElevation: CGFloat = 4
    static let capsuleCornerRadius: CGFloat = 16
    static let capsuleActiveAlpha: Double = 0.12
    static let capsuleInactiveAlpha: Double = 0.5
    static let overlayBubbleColor = Color(hex: "FF2D2D2D")
    static let overlayPanelCornerRadius: CGFloat = 12
    static let typingMs: Double = 400
    static let blinkMs: Double = 500
    static let circularButtonSize: CGFloat = 36
    static let circularButtonIconSize: CGFloat = 22
    static let brandGradientStart = Color(hex: "FF07C160")
    static let brandGradientEnd = Color(hex: "FF06AD56")
    static let userBubbleBg = Color(hex: "FF95EC69")
    static let userBubbleOn = Color(hex: "FF181818")
    static let tryChipHeight: CGFloat = 44
    static let inputBottomPadding: CGFloat = 28
    static let messageGap: CGFloat = 14
}

// MARK: - Chat Carousel（媒体结果横滑卡）

enum ChatCarouselTokens {
    static let cardWidth: CGFloat = 120
    static let cardHeight: CGFloat = 150
    static let cardCornerRadius: CGFloat = 12
    static let cardSpacing: CGFloat = 8
    static let feedbackButtonSize: CGFloat = 24
    static let feedbackIconColor = Color.white
    static let feedbackBgColor = Color(hex: "FF0F2B1B")
    static let viewAllCornerRadius: CGFloat = 12
}

// MARK: - Memory Page（回忆独立页分区大卡）

enum MemoryPageTokens {
    static let cardWidth: CGFloat = 168
    static let cardHeight: CGFloat = 224
    static let cardCornerRadius: CGFloat = 16
    static let cardSpacing: CGFloat = 12
    static let sectionHorizontalPadding: CGFloat = 16
    static let sectionTitleSpacing: CGFloat = 12
}

// MARK: - Chat Context（上下文附件暂存区）

enum ChatContextTokens {
    static let thumbSize: CGFloat = 72
    static let thumbCornerRadius: CGFloat = 8
    static let intentChipSpacing: CGFloat = 8
}

// MARK: - Chat Sidebar（侧栏抽屉）

enum ChatSidebarTokens {
    static let threadRadius: CGFloat = 8
    static let threadTitleSize: CGFloat = 15
    static let titleSize: CGFloat = 18
}

// MARK: - Settings

enum SettingsTokens {
    static let rowHeightNoSubtitle: CGFloat = 56
    static let rowHeightWithSubtitle: CGFloat = 64
    static let rowPaddingH: CGFloat = 12
    static let rowElementGap: CGFloat = 12
    static let rowLeadingIconSize: CGFloat = 24
    static let rowChevronSize: CGFloat = 20
    static let rowChevronAlpha: Double = 0.6
    static let toggleRowHeight: CGFloat = 44
    static let sectionPaddingH: CGFloat = 12
    static let sectionPaddingV: CGFloat = 10
    static let heroAvatarSize: CGFloat = 48
    static let categoryCardIconSize: CGFloat = 28
    static let listRowHeight: CGFloat = 56
    static let listHeroRowHeight: CGFloat = 72
    static let listRowPaddingH: CGFloat = 16
    static let listIconBlockSize: CGFloat = 28
    static let listIconBlockRadius: CGFloat = 7
    static let listIconInnerSize: CGFloat = 18
    static let listSectionSpacing: CGFloat = 8
    static let listSectionPaddingH: CGFloat = 16
    static let listDividerInsetStart: CGFloat = 56
    static let listTitleFontSize: CGFloat = 15
    static let listValueFontSize: CGFloat = 13
    static let listValueMaxWidth: CGFloat = 160
    static let listLabelColumnWidth: CGFloat = 56
    static let listSegmentedHeight: CGFloat = 36
    static let listSegmentedRadius: CGFloat = 10
    static let dialogOptionRowHeight: CGFloat = 48
}

// MARK: - Editor

enum EditorTokens {
    static let filterPanelHeight: CGFloat = 120
    static let filterItemWidth: CGFloat = 72
    static let filterThumbSize: CGFloat = 64
    static let filterLabelSize: CGFloat = 10
    static let filterSelectedBorderWidth: CGFloat = 3
    static let filterUnselectedBorderWidth: CGFloat = 1
    static let gachaCardThumbSize: CGFloat = 84
    static let gachaCardCornerRadius: CGFloat = 8
    static let gachaCardThumbCornerRadius: CGFloat = 6
    static let gachaBarBg = Color(hex: "FF1A1919")
    static let checkerboardCellSize: CGFloat = 16
    static let checkerboardLight = Color(hex: "FFE6E6E6")
    static let checkerboardDark = Color(hex: "FFBDBDBD")
    static let canvasDark = Color(hex: "FF0F0E0E")
    static let cropTransformButtonSize: CGFloat = 44
    static let cropTransformButtonBgAlpha: Double = 0.45
    static let overlayAlphaPrimary: Double = 0.06
    static let overlayAlphaHover: Double = 0.08
    static let overlayAlphaTrack: Double = 0.12
    static let adjustPanelMaxHeight: CGFloat = 220
    static let toolRailItemSize: CGFloat = 44
    static let paramTileSize: CGFloat = 54
    static let markupSwatchSelected: CGFloat = 32
    static let markupSwatchUnselected: CGFloat = 24
    static let canvasPureBlack = Color.black
    static let toolLabelSize: CGFloat = 10
    static let paramLabelSize: CGFloat = 13
    static let ratioChipSize: CGFloat = 44
    static let topBarButtonSize: CGFloat = 32
    static let unselectedLabelColor = Color(hex: "FF808080")
}

// MARK: - Grid

enum GridTokens {
    static let minCellSize: CGFloat = 110
    static let spacing: CGFloat = 2
    static let cornerRadius: CGFloat = 2
}

// MARK: - Gallery（相册页结构）

enum GalleryTokens {
    static let groupHeaderHeight: CGFloat = 36
    static let infoRowFontSize: CGFloat = 15
    static let statNumberFontSize: CGFloat = 17
    static let sortRowHeight: CGFloat = 40
}

// MARK: - SearchField（SearchTopBar 内嵌胶囊搜索框）

enum SearchFieldTokens {
    static let cornerRadius: CGFloat = 8
    static let paddingH: CGFloat = 12
    static let paddingV: CGFloat = 8
    static let backgroundAlpha: CGFloat = 0.7
    static let fontSize: CGFloat = 14
    static let iconGap: CGFloat = 8
    static let iconAlpha: CGFloat = 0.5
    static let placeholderAlpha: CGFloat = 0.4
    static let clearButtonSize: CGFloat = 20
    static let clearIconSize: CGFloat = 16
    static let resultCountFontSize: CGFloat = 12
    static let resultCountAlpha: CGFloat = 0.6
    static let resultCountGap: CGFloat = 8
    static let height: CGFloat = 36
}

// MARK: - Pager

enum PagerTokens {
    static let pageSpacing: CGFloat = 16
    static let actionIconSize: CGFloat = 32
    static let overlayMaxWidth: CGFloat = 393
    static let overlayMaxHeight: CGFloat = 500
}

// MARK: - Model Center

enum ModelCenterTokens {
    static let tagColorMustHave = Color(hex: "FFE53935")
    static let tagColorRecommended = Color(hex: "FFFF9800")
    static let tagColorChat = Color(hex: "FF576B95")
    static let tagColorPhotoTagging = Color(hex: "FF9C27B0")
    static let tagColorBeautyCamera = Color(hex: "FFFF9800")
    static let tagColorDefault = Color(hex: "FF9E9E9E")
    static let requiredBadgeBg = Color(hex: "FFE53935")
    static let chipHeight: CGFloat = 36
    static let chipIconSize: CGFloat = 14
    static let actionButtonSize: CGFloat = 36
    static let actionButtonSmallSize: CGFloat = 32
    static let tagBadgeRadius: CGFloat = 6
    static let miniBadgeRadius: CGFloat = 4
    static let tagBadgeDotSize: CGFloat = 6
}

// MARK: - Person（人物页列表+详情，聚类模型）

enum PersonTokens {
    static let cardRadius: CGFloat = 16
    static let gridColumns: Int = 2
    static let gridSpacing: CGFloat = 12
    static let coverAspectRatio: Double = 1.0
    static let detailCoverHeight: CGFloat = 180
    static let detailCoverWidthRatio: Double = 0.55
    static let coverPickerColumns: Int = 3
    static let nameFontSize: CGFloat = 16
    static let photoCountFontSize: CGFloat = 13
    static let relationChipRadius: CGFloat = 8
}

// MARK: - ID Photo（证照屏，强制深色）

enum IdPhotoTokens {
    static let screenBackground = Color(hex: "FF101010")
    static let tabUnselectedContainer = Color(hex: "FF2A2A2A")
    static let frameWidth: CGFloat = 220
    static let frameRadius: CGFloat = 4
    static let frameBackground = Color.white
    static let swatchSize: CGFloat = 40
    static let swatchSelectedBorderWidth: CGFloat = 3
    static let swatchUnselectedBorderWidth: CGFloat = 1
    static let sizeChipUnselectedBorderAlpha: Double = 0.5
    static let colorBlue = Color(hex: "FF438EDB")
    static let colorRed = Color(hex: "FFD9001B")
    static let colorWhite = Color.white
}

// MARK: - Color(hex:) 工具（ARGB 十六进制，与 JSON 一致）

private extension Color {
    init(hex: String) {
        let scanner = Scanner(string: hex)
        var hexNumber: UInt64 = 0
        scanner.scanHexInt64(&hexNumber)
        let a = Double((hexNumber & 0xFF00_0000) >> 24) / 255
        let r = Double((hexNumber & 0x00FF_0000) >> 16) / 255
        let g = Double((hexNumber & 0x0000_FF00) >> 8) / 255
        let b = Double(hexNumber & 0x0000_00FF) / 255
        self.init(.sRGB, red: r, green: g, blue: b, opacity: a)
    }
}
