package com.mamba.picme.core.designsystem

// ⚠️ GENERATED by scripts/gen-design-tokens.py — 勿手改；改 token 请改 design-tokens.json 后重跑生成器
// SSOT: shared/src/commonMain/resources/design-tokens.json

import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.ui.unit.dp

/** 全局圆角令牌。panel=底部面板顶角（仅顶部两角）；其余为全圆角。 */
object AppShapes {
    val panel = RoundedCornerShape(topStart = 12.dp, topEnd = 12.dp)
    val lg = RoundedCornerShape(16.dp)
    val card = RoundedCornerShape(8.dp)
    val button = RoundedCornerShape(10.dp)
    val small = RoundedCornerShape(8.dp)
    val thumbnail = RoundedCornerShape(2.dp)
}
