package com.mamba.picme.core.designsystem

// ⚠️ GENERATED by scripts/gen-design-tokens.py — 勿手改；改 token 请改 design-tokens.json 后重跑生成器
// SSOT: shared/src/commonMain/resources/design-tokens.json

import androidx.compose.ui.graphics.Color

// ── M3 baseline 配色（colorScheme.light/dark）──────────────────────────────────
// 注：ErrorLight 已按 SSOT 修正为 M3 标准 #B3261E（旧值 0xB32610 有 alpha=00 透明 bug）。

val PrimaryLight = Color(0xFF0E9F6E)
val OnPrimaryLight = Color.White
val PrimaryContainerLight = Color(0xFFC9EEDD)
val OnPrimaryContainerLight = Color(0xFF0B5C42)
val SecondaryLight = Color(0xFF5F9684)
val OnSecondaryLight = Color.White
val SecondaryContainerLight = Color(0xFFDCF2E5)
val OnSecondaryContainerLight = Color(0xFF124A38)
val TertiaryLight = Color(0xFF0B7A54)
val OnTertiaryLight = Color.White
val TertiaryContainerLight = Color(0xFFB9EAD3)
val OnTertiaryContainerLight = Color(0xFF053826)
val ErrorLight = Color(0xFFB3261E)
val OnErrorLight = Color.White
val ErrorContainerLight = Color(0xFFF9DEDC)
val OnErrorContainerLight = Color(0xFF410E0B)
val BackgroundLight = Color(0xFFF1FAF5)
val OnBackgroundLight = Color(0xFF0F3D2E)
val SurfaceLight = Color(0xFFF1FAF5)
val OnSurfaceLight = Color(0xFF0F3D2E)
val SurfaceVariantLight = Color(0xFFE0F4E8)
val OnSurfaceVariantLight = Color(0xFF5F9684)
val OutlineLight = Color(0xFF8CC0AC)
val OutlineVariantLight = Color(0xFFC8E5D4)
val SurfaceContainerLowestLight = Color.White
val SurfaceContainerLowLight = Color(0xFFEAF6EF)
val SurfaceContainerLight = Color(0xFFE8F8EF)
val SurfaceContainerHighLight = Color(0xFFE0F4E8)
val SurfaceContainerHighestLight = Color(0xFFD5EDDF)

val PrimaryDark = Color(0xFF2FE385)
val OnPrimaryDark = Color(0xFF062B18)
val PrimaryContainerDark = Color(0xFF1EA75B)
val OnPrimaryContainerDark = Color(0xFFC8F7DC)
val SecondaryDark = Color(0xFF8FBBA6)
val OnSecondaryDark = Color(0xFF06281A)
val SecondaryContainerDark = Color(0xFF10291C)
val OnSecondaryContainerDark = Color(0xFFCFEBDC)
val TertiaryDark = Color(0xFF6FD8A5)
val OnTertiaryDark = Color(0xFF042416)
val TertiaryContainerDark = Color(0xFF123B26)
val OnTertiaryContainerDark = Color(0xFFB2EFCB)
val ErrorDark = Color(0xFFF2B8B5)
val OnErrorDark = Color(0xFF601410)
val ErrorContainerDark = Color(0xFF8C1D18)
val OnErrorContainerDark = Color(0xFFF9DEDC)
val BackgroundDark = Color(0xFF071510)
val OnBackgroundDark = Color(0xFFDFF5E9)
val SurfaceDark = Color(0xFF071510)
val OnSurfaceDark = Color(0xFFDFF5E9)
val SurfaceVariantDark = Color(0xFF0F2B1B)
val OnSurfaceVariantDark = Color(0xFF8FBBA6)
val OutlineDark = Color(0xFF3E6B54)
val OutlineVariantDark = Color(0xFF1E4630)
val SurfaceContainerLowestDark = Color(0xFF04100A)
val SurfaceContainerLowDark = Color(0xFF0A1B13)
val SurfaceContainerDark = Color(0xFF0D2318)
val SurfaceContainerHighDark = Color(0xFF0F2B1B)
val SurfaceContainerHighestDark = Color(0xFF123B26)

// ── 功能色（color 组，不随主题切换）。引用方式：MaterialTheme.appColors.focusRing ──────────
val FocusRingColor = Color(0xFF00E5FF)
val PanelBackgroundColor = Color(0xCC000000)
val ShutterRingColor = Color(0xFFE4E4E4)
val SliderThumbColor = Color.White
val VibrantGreen = Color(0xFF00E676)
val VibrantBlue = Color(0xFF2979FF)
val VibrantOrange = Color(0xFFFF9100)
val VibrantPink = Color(0xFFFF4081)
val VibrantPurple = Color(0xFF4F378B)
val VibrantAmber = Color(0xFFFFA000)
val IconOnVibrantColor = Color.White
val WhiteColor = Color.White

/** 功能色集合，通过 [MaterialTheme.appColors] 访问。 */
object AppColors {
    val focusRing = FocusRingColor
    val panelBackground = PanelBackgroundColor
    val shutterRing = ShutterRingColor
    val sliderThumb = SliderThumbColor
    val vibrantGreen = VibrantGreen
    val vibrantBlue = VibrantBlue
    val vibrantOrange = VibrantOrange
    val vibrantPink = VibrantPink
    val vibrantPurple = VibrantPurple
    val vibrantAmber = VibrantAmber
    val iconOnVibrant = IconOnVibrantColor
    val white = WhiteColor
}
