package com.mamba.picme.core.designsystem

// ⚠️ GENERATED by scripts/gen-design-tokens.py — 勿手改；改 token 请改 design-tokens.json 后重跑生成器
// SSOT: shared/src/commonMain/resources/design-tokens.json

import androidx.compose.ui.graphics.Color

// ── M3 baseline 配色（colorScheme.light/dark）──────────────────────────────────
// 注：ErrorLight 已按 SSOT 修正为 M3 标准 #B3261E（旧值 0xB32610 有 alpha=00 透明 bug）。

val PrimaryLight = Color(0xFF07C160)
val OnPrimaryLight = Color.White
val PrimaryContainerLight = Color(0xFFD7F2E2)
val OnPrimaryContainerLight = Color(0xFF0A6B3F)
val SecondaryLight = Color(0xFF888888)
val OnSecondaryLight = Color.White
val SecondaryContainerLight = Color(0xFFF2F2F2)
val OnSecondaryContainerLight = Color(0xFF4D4D4D)
val TertiaryLight = Color(0xFF576B95)
val OnTertiaryLight = Color.White
val TertiaryContainerLight = Color(0xFFE9EDF5)
val OnTertiaryContainerLight = Color(0xFF3A4A6B)
val ErrorLight = Color(0xFFFA5151)
val OnErrorLight = Color.White
val ErrorContainerLight = Color(0xFFFDEBEB)
val OnErrorContainerLight = Color(0xFF8F1F1F)
val BackgroundLight = Color(0xFFEDEDED)
val OnBackgroundLight = Color(0xFF181818)
val SurfaceLight = Color(0xFFEDEDED)
val OnSurfaceLight = Color(0xFF181818)
val SurfaceVariantLight = Color(0xFFF2F2F2)
val OnSurfaceVariantLight = Color(0xFF888888)
val OutlineLight = Color(0xFFB2B2B2)
val OutlineVariantLight = Color(0xFFE5E5E5)
val SurfaceContainerLowestLight = Color.White
val SurfaceContainerLowLight = Color(0xFFF7F7F7)
val SurfaceContainerLight = Color(0xFFF7F7F7)
val SurfaceContainerHighLight = Color(0xFFEDEDED)
val SurfaceContainerHighestLight = Color(0xFFE5E5E5)
val WarmGrayIconLight = Color(0xFF888888)
val CellLight = Color.White

val PrimaryDark = Color(0xFF07C160)
val OnPrimaryDark = Color.White
val PrimaryContainerDark = Color(0xFF14562F)
val OnPrimaryContainerDark = Color(0xFFB7E9C9)
val SecondaryDark = Color(0xFF7F7F7F)
val OnSecondaryDark = Color.White
val SecondaryContainerDark = Color(0xFF2C2C2C)
val OnSecondaryContainerDark = Color(0xFFC9C9C9)
val TertiaryDark = Color(0xFF7D90B0)
val OnTertiaryDark = Color.White
val TertiaryContainerDark = Color(0xFF2A3346)
val OnTertiaryContainerDark = Color(0xFFC6D0E2)
val ErrorDark = Color(0xFFFA5151)
val OnErrorDark = Color.White
val ErrorContainerDark = Color(0xFF3A1F1F)
val OnErrorContainerDark = Color(0xFFF9DEDC)
val BackgroundDark = Color(0xFF111111)
val OnBackgroundDark = Color(0xFFD5D5D5)
val SurfaceDark = Color(0xFF111111)
val OnSurfaceDark = Color(0xFFD5D5D5)
val SurfaceVariantDark = Color(0xFF2C2C2C)
val OnSurfaceVariantDark = Color(0xFF7F7F7F)
val OutlineDark = Color(0xFF5F5F5F)
val OutlineVariantDark = Color(0xFF2C2C2C)
val SurfaceContainerLowestDark = Color(0xFF0C0C0C)
val SurfaceContainerLowDark = Color(0xFF141414)
val SurfaceContainerDark = Color(0xFF1A1A1A)
val SurfaceContainerHighDark = Color(0xFF222222)
val SurfaceContainerHighestDark = Color(0xFF2C2C2C)
val WarmGrayIconDark = Color(0xFF7F7F7F)
val CellDark = Color(0xFF1A1A1A)

// ── 功能色（color 组，不随主题切换）。引用方式：MaterialTheme.appColors.focusRing ──────────
val FocusRingColor = Color(0xFF00E5FF)
val PanelBackgroundColor = Color(0xCC000000)
val ProviderTagBgColor = Color(0xFF07C160)
val ProviderTagLabelColor = Color(0xFF067045)
val ShutterRingColor = Color(0xFFE4E4E4)
val SliderThumbColor = Color.White
val VibrantGreen = Color(0xFF00E676)
val VibrantBlue = Color(0xFF2979FF)
val VibrantOrange = Color(0xFFFF9100)
val VibrantPink = Color(0xFFFF4081)
val VibrantPurple = Color(0xFF4F378B)
val VibrantAmber = Color(0xFFFFA000)
val IconOnVibrantColor = Color.White
val VoiceButtonIconColor = Color(0xFF888888)
val WhiteColor = Color.White
val AmberColor = Color(0xFFFFB020)
val LavenderColor = Color(0xFFD0BCFF)
val MintColor = Color(0xFF8FD6C6)
val PaperWarmColor = Color(0xFFEDE9E3)
val SoftBlueColor = Color(0xFF6BA6FF)
val TagChipLineColor = Color(0xFF46413A)
val TagCyanColor = Color(0xFF22D3EE)
val TagGreenColor = Color(0xFF4ADE80)
val TagPinkColor = Color(0xFFFF7DB0)
val TagPurpleColor = Color(0xFF9C8CFF)

/** 功能色集合，通过 [MaterialTheme.appColors] 访问。 */
object AppColors {
    val focusRing = FocusRingColor
    val panelBackground = PanelBackgroundColor
    val providerTagBg = ProviderTagBgColor
    val providerTagLabel = ProviderTagLabelColor
    val shutterRing = ShutterRingColor
    val sliderThumb = SliderThumbColor
    val vibrantGreen = VibrantGreen
    val vibrantBlue = VibrantBlue
    val vibrantOrange = VibrantOrange
    val vibrantPink = VibrantPink
    val vibrantPurple = VibrantPurple
    val vibrantAmber = VibrantAmber
    val iconOnVibrant = IconOnVibrantColor
    val voiceButtonIcon = VoiceButtonIconColor
    val white = WhiteColor
    val amber = AmberColor
    val lavender = LavenderColor
    val mint = MintColor
    val paperWarm = PaperWarmColor
    val softBlue = SoftBlueColor
    val tagChipLine = TagChipLineColor
    val tagCyan = TagCyanColor
    val tagGreen = TagGreenColor
    val tagPink = TagPinkColor
    val tagPurple = TagPurpleColor
}
