package com.mamba.picme.core.designsystem

// ⚠️ GENERATED by scripts/gen-design-tokens.py — 勿手改；改 token 请改 design-tokens.json 后重跑生成器
// SSOT: shared/src/commonMain/resources/design-tokens.json

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp

/**
 * 组件级 token 镜像（与 iOS DesignTokens.swift 同源生成）。
 * 页面代码引用这些 object，禁止内联硬编码 dp/hex（漂移扫描见 DESIGN_TOKENS_SPEC.md §4）。
 */

/** strokeWidth=统一线性icon描边(2026-08-18 topbar/icon统一化,spec=docs/superpowers/specs/2026-08-18-ardot-topbar-icon-unification-design.md)。 */
object IconSize {
    val sm = 18.dp
    val md = 22.dp
    val lg = 24.dp
    val xl = 32.dp
    val strokeWidth = 1.6.dp
}

/** 透明度语义阶梯。绝大多数派生色 = colorScheme 角色 .copy(alpha=N)，如 onSurface@0.6=次要文本。iOS 须照搬这些 alpha 值以保证层级感还原。 */
object AppAlpha {
    val scrimModal = 0.7.dp
    val scrim = 0.55.dp
    val scrimDeep = 0.82.dp
    val surfaceTranslucent = 0.95.dp
    val fieldBackground = 0.7.dp
    val primaryTint = 0.12.dp
    val primaryTintSoft = 0.15.dp
    val primaryTintMedium = 0.2.dp
    val primaryTintStrong = 0.25.dp
    val emphasisHigh = 0.85.dp
    val emphasis = 0.8.dp
    val secondary = 0.6.dp
    val hint = 0.5.dp
    val placeholder = 0.4.dp
    val faint = 0.3.dp
    val ghost = 0.2.dp
}

/** 语义状态色（不随主题）。success/warning/error/info 跨 camera/chat/settings/idphoto/tag 复用。注意 statusError(#E53935)=产品 Material Red，与 colorScheme.error(#B3261E M3) 不同。 */
object StatusColor {
    val success = Color(0xFF4CAF50)
    val warning = Color(0xFFFF9800)
    val warningAmber = Color(0xFFFFA000)
    val error = Color(0xFFE53935)
    val info = Color(0xFF2196F3)
}

/** 动效时长(ms)+缓动。规范：禁用线性(Linear)，统一 FastOutSlowIn/Standard。drift: MainActivity nav 过渡 tween(400) 未指定 easing，应补 FastOutSlowIn。 */
object AppMotion {
    val instantMs = 80
    val fastMs = 150
    val mediumMs = 300
    val slowMs = 400
    val blinkMs = 500
    val pulseMs = 1200
    val staggerMs = 160
    val searchDebounceMs = 300
    val shutterDebounceMs = 500
    val galleryPreviewFadeMs = 300
    val galleryPreviewScaleMs = 400
    val galleryPreviewScaleFrom = 0.2f
    val galleryPreviewScaleTo = 1.0f
}

/** 阴影/tonal 阶梯(dp)。settings 卡片=none; 模型卡=low; 选中 chip/滑块 thumb=medium; chat 输入卡=high; 悬浮 Tab=floating; 底部面板=sheet。 */
object AppElevation {
    val none = 0.dp
    val low = 1.dp
    val medium = 2.dp
    val high = 4.dp
    val floating = 6.dp
    val sheet = 16.dp
}

/** AppTopBar 通用顶栏（Gallery/Settings/Editor 共享）。titleFontSize 17sp 为非 M3 标准定制值。 */
object TopBarTokens {
    val height = 48.dp
    val buttonSize = 36.dp
    val iconSize = 22.dp
    val titleFontSize = 17.dp
    val titleFontWeight = FontWeight.SemiBold
    val spacing = 8.dp
    val horizontalPadding = 8.dp
}

/** 相机快门。diameter=外环(#E4E4E4 实心圆); ringWidth=环厚((76-58)/2); innerDiameter=照片态内核(白); 录像态内核缩为 28dp 4dp 圆角方。 */
object ShutterTokens {
    val diameter = 76.dp
    val innerDiameter = 58.dp
    val recordingInnerDiameter = 28.dp
    val recordingInnerCornerRadius = 4.dp
    val ringWidth = 9.dp
    val pressDebounceMs = 500
    val flashAlpha = 0.6f
    val flashFadeMs = 80
}

/** 相机美颜面板容器（2026-08-18 三修回老版几何：圆角24/高0.4；色系走 cameraAccent）。slider 颜色见 appSlider CameraOverlay。 */
object BeautyPanelTokens {
    val topCornerRadius = 24.dp
    val iconSize = 24.dp
    val sliderThumbSize = 18.dp
    val sliderTrackHeight = 6.dp
    val heightRatio = 0.4f
    val heightRatioMin = 0.2f
    val heightRatioMax = 0.75f
}

/** 全 app 统一滑杆（HyperOS 风）：胶囊轨道+白圆点 primary 描边 thumb+按压放大。camera/editor/beauty 共享。颜色取 colorScheme.primary/onSurface。 */
object AppSliderTokens {
    val trackHeight = 6.dp
    val thumbSize = 18.dp
    val thumbPressedScale = 1.15f
    val thumbShadowElevation = 2.dp
    val thumbBorderWidth = 2.dp
    val thumbColor = Color.White
    val inactiveTrackAlpha = 0.12f
    val animDurationMs = 150
}

/** 悬浮底部胶囊导航（FloatingBottomTab），主入口聚合。v1 SSOT 漏配 cornerRadius=28，已补。color=surface。 */
object BottomTabTokens {
    val cornerRadius = 28.dp
    val tonalElevation = 3.dp
    val shadowElevation = 6.dp
    val containerPaddingH = 12.dp
    val containerPaddingV = 8.dp
    val itemPaddingH = 16.dp
    val itemPaddingVIconOnly = 10.dp
    val itemPaddingVWithLabel = 4.dp
    val iconSize = 24.dp
    val labelTopPadding = 2.dp
}

/** 相机/编辑器共享底部面板外壳（ControlPanel/BeautyPanel/ProMode/EditorPanel）。强制深色场景：surface@0.95 + 渐变 scrim。 */
object BottomSheetTokens {
    val topCornerRadius = 24.dp
    val shadowElevation = 16.dp
    val surfaceAlpha = 0.95f
    val borderWidth = 0.5.dp
    val borderColorAlpha = 0.25f
    val gradientStops: List<Color> = listOf(Color.Transparent, Color.Black.copy(alpha = 0.55f), Color.Black.copy(alpha = 0.82f))
    val handleWidth = 36.dp
    val handleHeight = 4.dp
    val handleColorAlpha = 0.2f
    val contentPaddingH = 24.dp
    val contentPaddingV = 8.dp
    val contentSpacing = 12.dp
}

/** 通用 FilterChip/AssistChip 几何。M3 默认组件 + 以下定制。selected=primary 系，unselected=surfaceVariant@0.5。 */
object ChipTokens {
    val height = 36.dp
    val smallHeight = 32.dp
    val unselectedContainerAlpha = 0.5f
    val selectedShadowElevation = 2.dp
}

/** 标签徽章（模型卡 tag badge / 模型 must-have 必备徽章）。primary@0.12 bg + 圆点。list*=设置列表行右侧计数徽章（2026-08-19 绑定清扫候选入库）。 */
object BadgeTokens {
    val tagRadius = 6.dp
    val tagBackgroundAlpha = 0.12f
    val tagDotSize = 6.dp
    val tagPaddingH = 8.dp
    val tagPaddingV = 3.dp
    val tagDotLabelGap = 4.dp
    val miniRadius = 4.dp
    val requiredRadius = 4.dp
    val requiredBg = Color(0xFFE53935)
    val requiredLabelWeight = FontWeight.Bold
    val requiredLabelColor = Color.White
    val listWidth = 44.dp
    val listHeight = 26.dp
}

/** 相机强制深色 overlay 专属（2026-08-18 按 Ardot 画布 specs/screens/refs/ardot/camera-*.png 高精度还原）。focusRing 复用 color.focusRing。cameraAccent=固定能量绿 #2FE385（主题无关单值；2026-09-13 v2.2.3 起，原深青玉 #0F766E 退役为主 accent，2026-09-20 以 tealAccent 名义随画布回流，仍用于个别工具 chip/辅助点缀）。 2026-09-22 v3.0 cameraAccent 换微信绿 #07C160。 */
object CameraTokens {
    val focusRingDiameter = 100.dp
    val focusRingStrokeWidth = 3.dp
    val focusRingCornerRadius = 20.dp
    val focusRingCrossLength = 16.dp
    val controlButtonSize = 48.dp
    val controlButtonIconSize = 24.dp
    val controlButtonIdleAlpha = 0.5f
    val modeTabFontSize = 13.dp
    val modeTabUnselectedAlpha = 1.0f
    val voicePulseMs = 1200
    val voicePulseAlphaFrom = 0.3f
    val voicePulseAlphaTo = 1.0f
    val filterSelectorColumns = 5
    val filterSelectorHeight = 280.dp
    val filterSelectedScale = 1.08f
    val filterSelectedBorderWidth = 2.5.dp
    val filterLabelFontSize = 10.dp
    val panelBackground = Color(0xB81C1A1F)
    val cameraAccent = Color(0xFF07C160)
    val cameraAccentOn = Color.White
    val toolBarUnselectedBg = Color(0x00000000)
    val inlineFilterPanelHeight = 200.dp
    val panelCornerRadius = 16.dp
    val panelMaxWidth = 420.dp
    val panelSideMargin = 28.dp
    val panelPaddingH = 16.dp
    val panelPaddingV = 10.dp
    val panelShadowElevation = 12.dp
    val chipHeight = 34.dp
    val chipPaddingH = 14.dp
    val chipSpacing = 10.dp
    val chipFontSize = 13.dp
    val wbChipPaddingH = 10.dp
    val wbChipSpacing = 8.dp
    val proSliderFontSize = 12.dp
    val topToolBarPaddingTop = 8.dp
    val topToolBarItemPaddingH = 10.dp
    val topToolBarItemPaddingV = 9.dp
    val topToolBarItemRadius = 10.dp
    val topToolBarSpacing = 6.dp
    val modeSwitcherSpacing = 24.dp
    val zoomBarSpacing = 12.dp
    val zoomCapsulePaddingH = 14.dp
    val zoomCapsuleHeight = 32.dp
    val zoomFontSize = 12.dp
    val zoomUnselectedBgAlpha = 0.5f
    val bottomControlsPaddingBottom = 60.dp
    val controlLabelFontSize = 11.dp
    val albumThumbColor = Color(0xFF404040)
    val albumPlaceholderIconColor = Color(0xFFE4E4E4)
    val flipIconColor = Color(0xFF1C1B1F)
    val wbChipFontSize = 12.dp
    val tealAccent = Color(0xFF0F766E)
    val toolChipBg = Color(0xFF4A454F)
}

/** 聊天气泡（2026-08-18 豆包范式，同日二修去头像）：AI 消息=无气泡+通栏纯文本；用户气泡=品牌实色 userBubbleBg；品牌渐变 brandGradientStart→End（发送钮/空态 Logo 与标题）；输入卡 r28+描边。userBubbleOn/tryChipHeight/inputBottomPadding/messageGap 2026-08-19 绑定清扫候选入库。 2026-09-22 v3.0 用户气泡换微信绿 #95EC69+深字（暗色变体待 B2 定）。 2026-09-22 v3.0.1 形态对齐：气泡 12+尾4、输入 8、弹层 12（spec §1）。 */
object ChatBubbleTokens {
    val bubbleMaxWidth = 360.dp
    val imageMaxWidth = 240.dp
    val paddingH = 18.dp
    val paddingV = 14.dp
    val cornerRadius = 12.dp
    val tailCornerRadius = 4.dp
    val textSize = 16.dp
    val textLineHeight = 24.dp
    val inputCornerRadius = 8.dp
    val inputShadowElevation = 4.dp
    val capsuleCornerRadius = 16.dp
    val capsuleActiveAlpha = 0.12f
    val capsuleInactiveAlpha = 0.5f
    val overlayBubbleColor = Color(0xFF2D2D2D)
    val overlayPanelCornerRadius = 12.dp
    val typingMs = 400
    val blinkMs = 500
    val circularButtonSize = 36.dp
    val circularButtonIconSize = 22.dp
    val brandGradientStart = Color(0xFF07C160)
    val brandGradientEnd = Color(0xFF06AD56)
    val userBubbleBg = Color(0xFF95EC69)
    val userBubbleOn = Color(0xFF181818)
    val tryChipHeight = 44.dp
    val inputBottomPadding = 28.dp
    val messageGap = 14.dp
}

/** 聊天媒体结果轮播（MediaResultsCarousel）。ios-follow chat 2026-08-12 自 Android MediaResultsCarousel.kt 反向提取。卡片右侧竖排反馈按钮叠层。 */
object ChatCarouselTokens {
    val cardWidth = 120.dp
    val cardHeight = 150.dp
    val cardCornerRadius = 12.dp
    val cardSpacing = 8.dp
    val feedbackButtonSize = 24.dp
    val feedbackIconColor = Color.White
    val feedbackBgColor = Color(0xFF0F2B1B)
    val viewAllCornerRadius = 12.dp
}

/** Memory 独立页（2026-09-06，对标小米相册时光大卡）：竖版 3:4 大卡横滑行。 */
object MemoryPageTokens {
    val cardWidth = 168.dp
    val cardHeight = 224.dp
    val cardCornerRadius = 16.dp
    val cardSpacing = 12.dp
    val sectionHorizontalPadding = 16.dp
    val sectionTitleSpacing = 12.dp
}

/** 聊天上下文附件暂存区（选图后输入栏上方）。ios-follow chat 2026-08-12 新增（B1）。72dp 缩略图 + 三意图 chip。 */
object ChatContextTokens {
    val thumbSize = 72.dp
    val thumbCornerRadius = 8.dp
    val intentChipSpacing = 8.dp
}

/** 侧栏抽屉（2026-08-19 绑定清扫候选入库）：threadRadius=会话条圆角; threadTitleSize=会话条标题字号; titleSize=抽屉主标题字号。 */
object ChatSidebarTokens {
    val threadRadius = 8.dp
    val threadTitleSize = 15.dp
    val titleSize = 18.dp
}

/** 设置页通用结构。SettingsClickableRow=主行模式，section=分组卡片容器。list*=主菜单列表式（2026-08-17 重设计，iOS 式分组列表）；图标块色映射（行到 vibrant 系、statusColor、colorScheme 角色的对应）属 UI 结构不入 token，双端各自在代码中映射并保持一致。listLabelColumnWidth/listSegmentedHeight/listSegmentedRadius 2026-08-19 自画布回流（sync --check NEW）；dialogOptionRowHeight 2026-08-19 绑定清扫候选入库；themeSwatch* 同日随主题弹框预览块删除而撤销（0edd118d3）；listDividerColor 同日撤销——分隔线改绑 scheme/outlineVariant（双 mode，浅色下不再呈深线）。注意注释内勿出现连续斜杠星号（会截断 Android KDoc 块注释）。 */
object SettingsTokens {
    val rowHeightNoSubtitle = 56.dp
    val rowHeightWithSubtitle = 64.dp
    val rowPaddingH = 12.dp
    val rowElementGap = 12.dp
    val rowLeadingIconSize = 24.dp
    val rowChevronSize = 20.dp
    val rowChevronAlpha = 0.6f
    val toggleRowHeight = 44.dp
    val sectionPaddingH = 12.dp
    val sectionPaddingV = 10.dp
    val heroAvatarSize = 48.dp
    val categoryCardIconSize = 28.dp
    val listRowHeight = 56.dp
    val listHeroRowHeight = 72.dp
    val listRowPaddingH = 16.dp
    val listIconBlockSize = 28.dp
    val listIconBlockRadius = 7.dp
    val listIconInnerSize = 18.dp
    val listSectionSpacing = 24.dp
    val listSectionPaddingH = 16.dp
    val listDividerInsetStart = 56.dp
    val listTitleFontSize = 15.dp
    val listValueFontSize = 13.dp
    val listValueMaxWidth = 160.dp
    val listLabelColumnWidth = 56.dp
    val listSegmentedHeight = 36.dp
    val listSegmentedRadius = 10.dp
    val dialogOptionRowHeight = 48.dp
}

/** 图片编辑器组件几何（结构 token）。内容色板（markup 7 色/lip 12 色/blush 3 色）见 DESIGN_TOKENS_SPEC.md palette 附录，属产品内容数据不入 token。2026-08-19 editor.yaml §18 redesign_a 提案入库：canvasDark/gachaBarBg/overlayAlpha 三档（glassOverlay white@0.06/0.08 拆分）/toolRailItemSize/paramTileSize。canvasPureBlack/toolLabelSize/paramLabelSize/ratioChipSize/topBarButtonSize/unselectedLabelColor 2026-08-19 绑定清扫候选入库。 */
object EditorTokens {
    val filterPanelHeight = 120.dp
    val filterItemWidth = 72.dp
    val filterThumbSize = 64.dp
    val filterLabelSize = 10.dp
    val filterSelectedBorderWidth = 3.dp
    val filterUnselectedBorderWidth = 1.dp
    val gachaCardThumbSize = 84.dp
    val gachaCardCornerRadius = 8.dp
    val gachaCardThumbCornerRadius = 6.dp
    val gachaBarBg = Color(0xFF1A1919)
    val checkerboardCellSize = 16.dp
    val checkerboardLight = Color(0xFFE6E6E6)
    val checkerboardDark = Color(0xFFBDBDBD)
    val canvasDark = Color(0xFF0F0E0E)
    val cropTransformButtonSize = 44.dp
    val cropTransformButtonBgAlpha = 0.45f
    val overlayAlphaPrimary = 0.06f
    val overlayAlphaHover = 0.08f
    val overlayAlphaTrack = 0.12f
    val adjustPanelMaxHeight = 220.dp
    val toolRailItemSize = 44.dp
    val paramTileSize = 54.dp
    val markupSwatchSelected = 32.dp
    val markupSwatchUnselected = 24.dp
    val canvasPureBlack = Color.Black
    val toolLabelSize = 10.dp
    val paramLabelSize = 13.dp
    val ratioChipSize = 44.dp
    val topBarButtonSize = 32.dp
    val unselectedLabelColor = Color(0xFF808080)
}

/** 相册/搜索网格。方形 Crop，minCellSize 控制列数。 */
object GridTokens {
    val minCellSize = 110.dp
    val spacing = 2.dp
    val cornerRadius = 2.dp
}

/** 相册页结构（2026-08-19 绑定清扫候选入库）：groupHeaderHeight=日期分组头高; infoRowFontSize=资产信息行字号; statNumberFontSize=统计数字字号; sortRowHeight=排序菜单行高。 */
object GalleryTokens {
    val groupHeaderHeight = 36.dp
    val infoRowFontSize = 15.dp
    val statNumberFontSize = 17.dp
    val sortRowHeight = 40.dp
}

/** SearchTopBar 内嵌胶囊搜索框（Gallery/Chat 共用 SearchField）。ios-follow gallery-search 2026-08-11 自 Android SearchField.kt 反向提取。颜色全走 colorScheme 角色：bg=surfaceVariant@0.7，icon/placeholder/clear=onSurface@0.5/0.4/0.5，cursor=primary。height=整胶囊高度（2026-08-19 绑定清扫候选入库）。 */
object SearchFieldTokens {
    val cornerRadius = 8.dp
    val paddingH = 12.dp
    val paddingV = 8.dp
    val backgroundAlpha = 0.7f
    val fontSize = 14.dp
    val iconGap = 8.dp
    val iconAlpha = 0.5f
    val placeholderAlpha = 0.4f
    val clearButtonSize = 20.dp
    val clearIconSize = 16.dp
    val resultCountFontSize = 12.dp
    val resultCountAlpha = 0.6f
    val resultCountGap = 8.dp
    val height = 36.dp
}

/** 5 页 App Shell（Gallery=0/Organize=1/Chat=2/People=3/Memory=4）HorizontalPager（2026-09-06 主导航统一，相机已移出 Pager 改全屏路由）。overlayMaxWidth 2026-08-19 迁移 iPhone 15 画布宽 400→393。 */
object PagerTokens {
    val pageSpacing = 16.dp
    val actionIconSize = 32.dp
    val overlayMaxWidth = 393.dp
    val overlayMaxHeight = 500.dp
}

/** 模型下载中心专属 token。getTagColor 代码用主题角色(recommended/chat/beauty-camera→tertiary/primary)与下方固定 hex 存在分歧，iOS 以本表固定 hex 为准。 */
object ModelCenterTokens {
    val tagColorMustHave = Color(0xFFE53935)
    val tagColorRecommended = Color(0xFFFF9800)
    val tagColorChat = Color(0xFF2196F3)
    val tagColorPhotoTagging = Color(0xFF9C27B0)
    val tagColorBeautyCamera = Color(0xFFFF9800)
    val tagColorDefault = Color(0xFF9E9E9E)
    val requiredBadgeBg = Color(0xFFE53935)
    val chipHeight = 36.dp
    val chipIconSize = 14.dp
    val actionButtonSize = 36.dp
    val actionButtonSmallSize = 32.dp
    val tagBadgeRadius = 6.dp
    val miniBadgeRadius = 4.dp
    val tagBadgeDotSize = 6.dp
}

/** 人物页（列表+详情）。聚类模型，对标 Android PersonScreen/PersonInfoScreen。cardRadius=16 区别于通用 radius.card=12（Android PersonListItem 显式 16dp）。 */
object PersonTokens {
    val cardRadius = 16.dp
    val gridColumns = 2
    val gridSpacing = 12.dp
    val coverAspectRatio = 1.0f
    val detailCoverHeight = 180.dp
    val detailCoverWidthRatio = 0.55f
    val coverPickerColumns = 3
    val nameFontSize = 16.dp
    val photoCountFontSize = 13.dp
    val relationChipRadius = 8.dp
}

/** 证照屏（IDPhoto）。强制深色屏：内容底近黑硬编码，Android PoLangForcedDarkTheme / iOS .preferredColorScheme(.dark)+AppColorScheme.dark 对齐 scheme。colorBlue/Red/White 为合成内容色（既作底色数据也作色板 UI 色，双端像素一致）。 */
object IdPhotoTokens {
    val screenBackground = Color(0xFF101010)
    val tabUnselectedContainer = Color(0xFF2A2A2A)
    val frameWidth = 220.dp
    val frameRadius = 4.dp
    val frameBackground = Color.White
    val swatchSize = 40.dp
    val swatchSelectedBorderWidth = 3.dp
    val swatchUnselectedBorderWidth = 1.dp
    val sizeChipUnselectedBorderAlpha = 0.5f
    val colorBlue = Color(0xFF438EDB)
    val colorRed = Color(0xFFD9001B)
    val colorWhite = Color.White
}
