#!/usr/bin/env python3
"""
PoLang Design Token 代码生成器（双端镜像防漂移）

SSOT: shared/src/commonMain/resources/design-tokens.json
产物（全部为生成物，禁止手改）：
  - iosApp/PoLang/DesignSystem/DesignTokens.swift
  - androidApp/src/main/java/com/mamba/picme/core/designsystem/Spacing.kt
  - androidApp/src/main/java/com/mamba/picme/core/designsystem/AppShapes.kt
  - androidApp/src/main/java/com/mamba/picme/core/designsystem/Color.kt
  - androidApp/src/main/java/com/mamba/picme/core/designsystem/Typography.kt
  - androidApp/src/main/java/com/mamba/picme/core/designsystem/DesignTokens.kt（组件级 token）
  - build/design-tokens/ardot-variables.json（Ardot apply_variables 预览层输入）

Ardot 画布双向同步：本文件只读 SSOT 单向生成；画布↔JSON 的 --push/--pull/--check
（含 gen_ardot_payload 的精确逆变换）见 scripts/sync-ardot-variables.py。

用法：
  python3 scripts/gen-design-tokens.py           # 就地生成/覆盖所有产物
  python3 scripts/gen-design-tokens.py --check   # 校验模式：与磁盘 diff，不一致 exit 1（CI 门禁）

类型规约（convention-over-config，例外见 OVERRIDE 表）：
  - 数值：尺寸类 → dp/CGFloat；*Ms → Int(Android)/Double(Swift)；含 alpha/ratio/scale 的浮点 → Float/Double
  - INT_KEYS 中的键 → Int（双端）
  - 字符串：#AARRGGBB → Color；*Weight ∈ {Normal,Medium,SemiBold,Bold} → Font.Weight/FontWeight；其余视为语义引用跳过
    （"@xxx" 占位的 Swift 侧语义引用可经 RAW_SWIFT_VALUES 表直出 Swift 属性行，Android 侧不生成）
  - 颜色捷径：#FFFFFFFF → white；#FF000000 → black；带 alpha 的纯白/纯黑 → white/black.opacity(a)
  - 嵌套 dict：typography/colorScheme/motion 走专用模板；其余按 parentKey+Capitalized(childKey) 拍平
"""

import difflib
import json
import re
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
JSON_PATH = PROJECT_ROOT / "shared/src/commonMain/resources/design-tokens.json"
IOS_OUT = PROJECT_ROOT / "iosApp/PoLang/DesignSystem/DesignTokens.swift"
ANDROID_DS = PROJECT_ROOT / "androidApp/src/main/java/com/mamba/picme/core/designsystem"
ARDOT_OUT = PROJECT_ROOT / "build/design-tokens/ardot-variables.json"

GENERATED_BANNER = "⚠️ GENERATED by scripts/gen-design-tokens.py — 勿手改；改 token 请改 design-tokens.json 后重跑生成器"

# ── 例外表 ────────────────────────────────────────────────────────────────────
# 双端都是 Int 的键（计数/列数）
INT_KEYS = {"filterSelectorColumns", "gridColumns", "coverPickerColumns"}
# Swift 侧历史遗留：searchField 的 alpha 是 CGFloat（其余组 alpha 均为 Double）。保持等价，后续可统一。
# beautyPanel.heightRatio：iOS ControlPanel(heightRatio:) 形参为 CGFloat，需 CGFloat 直出。
SWIFT_CG_FLOAT_KEYS = {("searchField", "backgroundAlpha"), ("searchField", "iconAlpha"),
                       ("searchField", "placeholderAlpha"), ("searchField", "resultCountAlpha"),
                       ("beautyPanel", "heightRatio")}
# Swift 侧语义引用值的原始直出（JSON 中 "@xxx" 占位字符串 classify 为 skip，Android 侧不生成——
# Android 对应语义走 colorScheme 角色，如相机 accent=primary）：
# (group, key) → Swift 属性行（不含缩进），追加在该 group 枚举末尾。
RAW_SWIFT_VALUES = {
    # 相机 accent 2026-08-18 起按 Ardot 定稿冻结为固定深青玉 #0F766E（design-tokens.json 直存 hex，双端正常生成）
    ("camera", "toolBarSelectedBg"): "static let toolBarSelectedBg: Color = CameraTokens.cameraAccent",
}
# 显式跳过的键（语义引用或历史未镜像）：(group, key)
SKIP_KEYS = {("camera", "modeTabSelectedWeight")}
# 枚举名映射（group → Swift enum / Kotlin object 名）
ENUM_NAMES = {
    "spacing": "Spacing", "radius": "AppRadius", "icon": "IconSize",
    "topBar": "TopBarTokens", "shutter": "ShutterTokens", "beautyPanel": "BeautyPanelTokens",
    "grid": "GridTokens", "searchField": "SearchFieldTokens", "pager": "PagerTokens",
    "color": "AppColors", "alpha": "AppAlpha", "statusColor": "StatusColor",
    "elevation": "AppElevation", "appSlider": "AppSliderTokens", "bottomTab": "BottomTabTokens",
    "bottomSheet": "BottomSheetTokens", "chip": "ChipTokens", "badge": "BadgeTokens",
    "camera": "CameraTokens", "chatBubble": "ChatBubbleTokens", "chatCarousel": "ChatCarouselTokens",
    "memoryPage": "MemoryPageTokens",
    "chatContext": "ChatContextTokens", "chatSidebar": "ChatSidebarTokens", "settings": "SettingsTokens",
    "editor": "EditorTokens", "gallery": "GalleryTokens",
    "modelCenter": "ModelCenterTokens", "person": "PersonTokens", "motion": "AppMotion",
    "idphoto": "IdPhotoTokens",
}
# iOS 文件中的枚举输出顺序（含专用模板位置）
IOS_ORDER = ["spacing", "radius", "icon", "color", "typography", "colorScheme", "alpha",
             "statusColor", "motion", "elevation", "topBar", "shutter", "beautyPanel",
             "appSlider", "bottomTab", "bottomSheet", "chip", "badge", "camera",
             "chatBubble", "chatCarousel", "memoryPage", "chatContext", "chatSidebar", "settings", "editor",
             "grid", "gallery", "searchField", "pager", "modelCenter", "person", "idphoto"]
# Android 组件 token 文件的 object 顺序（spacing/radius/color/typography/colorScheme 有独立文件，不重复）
ANDROID_TOKENS_ORDER = ["icon", "alpha", "statusColor", "motion", "elevation", "topBar",
                        "shutter", "beautyPanel", "appSlider", "bottomTab", "bottomSheet",
                        "chip", "badge", "camera", "chatBubble", "chatCarousel", "memoryPage", "chatContext",
                        "chatSidebar", "settings", "editor", "grid", "gallery", "searchField", "pager",
                        "modelCenter", "person", "idphoto"]

SWIFT_WEIGHTS = {"Normal": ".regular", "Medium": ".medium", "SemiBold": ".semibold", "Bold": ".bold"}
KOTLIN_WEIGHTS = {"Normal": "FontWeight.Normal", "Medium": "FontWeight.Medium",
                  "SemiBold": "FontWeight.SemiBold", "Bold": "FontWeight.Bold"}

HEX_RE = re.compile(r"^#([0-9A-Fa-f]{6}|[0-9A-Fa-f]{8})$")


def fmt_num(v):
    """数字格式化：int 原样；float 去尾零（1.0 → '1.0'，0.50 → '0.5'）。"""
    if isinstance(v, bool):
        raise TypeError("bool 不是合法 token 值")
    if isinstance(v, int):
        return str(v)
    s = repr(float(v))
    return s


def classify(group, key, value):
    """叶子值分类 → (kind, …)。kind ∈ size|int|ms|float|color|weight|skip|nested|array"""
    if key.startswith("_"):
        return ("skip",)
    if (group, key) in SKIP_KEYS:
        return ("skip",)
    if isinstance(value, dict):
        return ("nested", value)
    if isinstance(value, list):
        return ("array", value)
    if isinstance(value, str):
        if HEX_RE.match(value):
            return ("color", value)
        if key.endswith("Weight") and value in SWIFT_WEIGHTS:
            return ("weight", value)
        return ("skip",)  # 语义引用（primary/surfaceVariant/capsule/easing 等），不进代码常量
    if isinstance(value, (int, float)):
        if key in INT_KEYS:
            return ("int", value)
        if key.endswith("Ms"):
            return ("ms", value)
        if isinstance(value, float) and any(t in key.lower() for t in ("alpha", "ratio", "scale")):
            return ("float", value)
        return ("size", value)
    return ("skip",)


def flatten(group, data):
    """把 group dict 拍平成 [(name, kind, value)]。嵌套 dict 按 parentKey+Child 展开一层。"""
    out = []
    for key, value in data.items():
        kind, *rest = classify(group, key, value)
        if kind == "nested":
            for child_key, child_value in rest[0].items():
                if child_key.startswith("_"):
                    continue
                ck = key + child_key[0].upper() + child_key[1:]
                ckind, *crest = classify(group, ck, child_value)
                if ckind in ("size", "int", "ms", "float", "color", "weight"):
                    out.append((ck, ckind, crest[0]))
        elif kind in ("size", "int", "ms", "float", "color", "weight", "array"):
            out.append((key, kind, rest[0] if rest else None))
    return out


def parse_hex(hex_str):
    """#AARRGGBB / #RRGGBB → (r, g, b, a) 0-1 浮点。"""
    h = hex_str.lstrip("#")
    if len(h) == 6:
        h = "FF" + h
    a = int(h[0:2], 16) / 255
    r = int(h[2:4], 16) / 255
    g = int(h[4:6], 16) / 255
    b = int(h[6:8], 16) / 255
    return r, g, b, a


def swift_color(hex_str):
    r, g, b, a = parse_hex(hex_str)
    if a != 1.0:
        return f'Color(hex: "{hex_str.lstrip("#")}")'
    if (r, g, b) == (1.0, 1.0, 1.0):
        return "Color.white"
    if (r, g, b) == (0.0, 0.0, 0.0):
        return "Color.black"
    return f'Color(hex: "{hex_str.lstrip("#")}")'


def kotlin_color(hex_str):
    r, g, b, a = parse_hex(hex_str)
    if a != 1.0:
        return f"Color(0x{hex_str.lstrip('#')})"
    if (r, g, b) == (1.0, 1.0, 1.0):
        return "Color.White"
    if (r, g, b) == (0.0, 0.0, 0.0):
        return "Color.Black"
    return f"Color(0x{hex_str.lstrip('#')})"


def gradient_swift(stops):
    """gradientStops: ["transparent", "black@0.55"] → SwiftUI Color 数组行。"""
    items = []
    for s in stops:
        if s == "transparent":
            items.append("Color.clear")
        elif "@" in s:
            base, alpha = s.split("@", 1)
            items.append(f"Color.{base}.opacity({alpha})")
        else:
            items.append(f"Color.{s}")
    return items


def gradient_kotlin(stops):
    items = []
    for s in stops:
        if s == "transparent":
            items.append("Color.Transparent")
        elif "@" in s:
            base, alpha = s.split("@", 1)
            items.append(f"Color.{base.capitalize()}.copy(alpha = {alpha}f)")
        else:
            items.append(f"Color.{base.capitalize()}")
    return items


# ── Swift 发射器 ──────────────────────────────────────────────────────────────

def swift_prop_line(group, name, kind, value):
    if kind == "size":
        return f"    static let {name}: CGFloat = {fmt_num(value)}"
    if kind == "int":
        return f"    static let {name}: Int = {fmt_num(value)}"
    if kind == "ms":
        return f"    static let {name}: Double = {fmt_num(value)}"
    if kind == "float":
        if (group, name) in SWIFT_CG_FLOAT_KEYS:
            return f"    static let {name}: CGFloat = {fmt_num(value)}"
        return f"    static let {name}: Double = {fmt_num(value)}"
    if kind == "color":
        return f"    static let {name} = {swift_color(value)}"
    if kind == "weight":
        return f"    static let {name}: Font.Weight = {SWIFT_WEIGHTS[value]}"
    if kind == "array":  # 目前仅 gradientStops
        items = gradient_swift(value)
        body = "\n".join(f"        {it}," for it in items).rstrip(",")
        return f"    static let {name}: [Color] = [\n{body}\n    ]"
    raise ValueError(f"未知 kind: {kind}")


def swift_simple_enum(group, data):
    lines = [f"enum {ENUM_NAMES[group]} {{"]
    for name, kind, value in flatten(group, data):
        lines.append(swift_prop_line(group, name, kind, value))
    for (raw_group, _key), raw_line in RAW_SWIFT_VALUES.items():
        if raw_group == group:
            lines.append(f"    {raw_line}")
    lines.append("}")
    return "\n".join(lines)


def swift_typography(data):
    roles = [(k, v) for k, v in data.items() if not k.startswith("_")]
    lines = [
        "/// 字号角色。`font` 直接产出 SwiftUI Font；`lineHeight`/`letterSpacing` 供 `.lineSpacing`/`.tracking` 使用。",
        "struct TypeStyle {",
        "    let size: CGFloat",
        "    let lineHeight: CGFloat",
        "    let weight: Font.Weight",
        "    let letterSpacing: CGFloat",
        "",
        "    var font: Font { .system(size: size, weight: weight) }",
        "}",
        "",
        "enum AppTypography {",
    ]
    for role, spec in roles:
        lines.append(
            f"    static let {role} = TypeStyle(size: {fmt_num(spec['size'])}, "
            f"lineHeight: {fmt_num(spec['lineHeight'])}, weight: {SWIFT_WEIGHTS[spec['weight']]}, "
            f"letterSpacing: {fmt_num(spec['letterSpacing'])})"
        )
    lines += [
        "",
        "    /// 内联字重覆盖（Android 在 M3 role 之上叠加：模型卡名 SemiBold、必备徽章 Bold 等）。",
        "    enum WeightOverride {",
        "        static let semibold: Font.Weight = .semibold",
        "        static let bold: Font.Weight = .bold",
        "    }",
        "}",
    ]
    return "\n".join(lines)


def swift_color_scheme(data):
    light = data["light"]
    dark = data["dark"]
    keys = list(light.keys())
    lines = [
        "/// 一组随主题切换的语义色。Android 12+ 走 Material You 动态取色，iOS 无等价物，统一用此基准。",
        "/// 已修正 Android 端两处 bug：ErrorLight alpha=00 透明、Dark tertiaryContainer 误指 TertiaryDark。",
        "struct SchemeColors {",
    ]
    lines += [f"    let {k}: Color" for k in keys]
    lines += ["}", "", "enum AppColorScheme {"]
    for mode_name, mode in (("light", light), ("dark", dark)):
        lines.append(f"    static let {mode_name} = SchemeColors(")
        for i, k in enumerate(keys):
            sep = "," if i < len(keys) - 1 else ""
            lines.append(f"        {k}: {swift_color(mode[k])}{sep}")
        lines.append("    )" + ("\n" if mode_name == "light" else ""))
    lines.append("}")
    return "\n".join(lines)


def swift_motion(data):
    dur = data["durationMs"]
    gp = data["galleryPreview"]
    return "\n".join([
        "/// FastOutSlowInEasing 在 SwiftUI 的等价是 `.easeInOut`；禁用线性动画。",
        "enum AppMotion {",
        *[f"    static let {k}Ms: Double = {fmt_num(v)}" for k, v in dur.items()],
        "",
        f"    static let staggerMs: Double = {fmt_num(data['staggerMs'])}",
        f"    static let searchDebounceMs: Double = {fmt_num(data['searchDebounceMs'])}",
        f"    static let shutterDebounceMs: Double = {fmt_num(data['shutterDebounceMs'])}",
        "",
        "    /// 相册预览进场（fade + scale，scale 0.2↔1.0）。",
        f"    static let galleryPreviewFadeMs: Double = {fmt_num(gp['fadeMs'])}",
        f"    static let galleryPreviewScaleMs: Double = {fmt_num(gp['scaleMs'])}",
        f"    static let galleryPreviewScaleFrom: CGFloat = {fmt_num(gp['scaleFrom'])}",
        f"    static let galleryPreviewScaleTo: CGFloat = {fmt_num(gp['scaleTo'])}",
        "}",
    ])


MARK_NAMES = {
    "spacing": "Spacing", "radius": "Radius", "icon": "Icon Sizes",
    "color": "App Colors（不随主题切换的固定功能色）", "typography": "Typography（M3 baseline 字号阶梯，仅 bodyLarge 为定制）",
    "colorScheme": "Color Scheme（M3 baseline，iOS 无动态取色，以此为语义色基准）",
    "alpha": "Alpha（透明度语义阶梯）", "statusColor": "Status Color（语义状态色，不随主题）",
    "motion": "Motion（动效时长 + 缓动）", "elevation": "Elevation（阴影/tonal 阶径）",
    "topBar": "TopBar", "shutter": "Shutter", "beautyPanel": "Beauty Panel",
    "appSlider": "App Slider（全 app 统一滑杆）", "bottomTab": "Bottom Tab（悬浮胶囊导航）",
    "bottomSheet": "Bottom Sheet（相机/编辑器共享面板外壳）", "chip": "Chip", "badge": "Badge",
    "camera": "Camera（强制深色 overlay）", "chatBubble": "Chat Bubble",
    "chatCarousel": "Chat Carousel（媒体结果横滑卡）", "memoryPage": "Memory Page（回忆独立页分区大卡）", "chatContext": "Chat Context（上下文附件暂存区）",
    "chatSidebar": "Chat Sidebar（侧栏抽屉）",
    "settings": "Settings", "editor": "Editor", "grid": "Grid", "gallery": "Gallery（相册页结构）",
    "searchField": "SearchField（SearchTopBar 内嵌胶囊搜索框）", "pager": "Pager",
    "modelCenter": "Model Center", "person": "Person（人物页列表+详情，聚类模型）",
    "idphoto": "ID Photo（证照屏，强制深色）",
}


def gen_swift(tokens):
    parts = [
        "import SwiftUI",
        "import Foundation",
        "",
        f"// MARK: - Design Tokens（{GENERATED_BANNER}）",
        "//",
        "// SSOT: shared/src/commonMain/resources/design-tokens.json",
        "// 所有新增 UI 必须引用这些常量，禁止硬编码尺寸/颜色/圆角。",
        "// 完整提取方法学/漂移记录/内容色板见 docs/03-TECHNICAL-SPECS/DESIGN_TOKENS_SPEC.md。",
    ]
    for group in IOS_ORDER:
        data = tokens[group]
        parts += ["", f"// MARK: - {MARK_NAMES[group]}", ""]
        if group == "typography":
            parts.append(swift_typography(data))
        elif group == "colorScheme":
            parts.append(swift_color_scheme(data))
            parts += [
                "",
                "// MARK: - Scheme 解析（跨屏共享）",
                "",
                "/// 按当前主题取 M3 语义色组。用法：`@Environment(\\.colorScheme)` + `let s = appScheme(cs)`。",
                "/// 各屏统一经此消费语义色，禁止硬编码 Color.white/opacity 近似（[PARITY] 契约色以 design-tokens.json 为准）。",
                "func appScheme(_ cs: ColorScheme) -> SchemeColors {",
                "    cs == .dark ? AppColorScheme.dark : AppColorScheme.light",
                "}",
            ]
        elif group == "motion":
            parts.append(swift_motion(data))
        elif group == "radius":
            parts.append(swift_simple_enum(group, data))
            parts += [
                "",
                "enum AppShapes {",
            ]
            for key, value in data.items():
                if key.startswith("_"):
                    continue
                parts.append(f"    static let {key} = RoundedRectangle(cornerRadius: AppRadius.{key}, style: .continuous)")
            parts.append("}")
        else:
            parts.append(swift_simple_enum(group, data))
    parts += [
        "",
        "// MARK: - Color(hex:) 工具（ARGB 十六进制，与 JSON 一致）",
        "",
        "private extension Color {",
        "    init(hex: String) {",
        "        let scanner = Scanner(string: hex)",
        "        var hexNumber: UInt64 = 0",
        "        scanner.scanHexInt64(&hexNumber)",
        "        let a = Double((hexNumber & 0xFF00_0000) >> 24) / 255",
        "        let r = Double((hexNumber & 0x00FF_0000) >> 16) / 255",
        "        let g = Double((hexNumber & 0x0000_FF00) >> 8) / 255",
        "        let b = Double(hexNumber & 0x0000_00FF) / 255",
        "        self.init(.sRGB, red: r, green: g, blue: b, opacity: a)",
        "    }",
        "}",
        "",
    ]
    return "\n".join(parts)


# ── Kotlin 发射器 ─────────────────────────────────────────────────────────────

KT_PACKAGE = "package com.mamba.picme.core.designsystem"


def kt_header(comment):
    return f"{KT_PACKAGE}\n\n// {GENERATED_BANNER}\n// SSOT: shared/src/commonMain/resources/design-tokens.json\n\n{comment}"


def gen_kotlin_spacing(tokens):
    lines = [kt_header("import androidx.compose.ui.unit.dp\n"),
             "/** 全局间距令牌。引用方式：`MaterialTheme.spacing.sm` 或直接 `Spacing.sm`。 */",
             "object Spacing {"]
    for key, value in tokens["spacing"].items():
        if key.startswith("_"):
            continue
        lines.append(f"    val {key} = {fmt_num(value)}.dp")
    lines.append("}")
    return "\n".join(lines) + "\n"


def gen_kotlin_shapes(tokens):
    lines = [kt_header("import androidx.compose.foundation.shape.RoundedCornerShape\nimport androidx.compose.ui.unit.dp\n"),
             "/** 全局圆角令牌。panel=底部面板顶角（仅顶部两角）；其余为全圆角。 */",
             "object AppShapes {"]
    for key, value in tokens["radius"].items():
        if key.startswith("_"):
            continue
        if key == "panel":
            lines.append(f"    val panel = RoundedCornerShape(topStart = {fmt_num(value)}.dp, topEnd = {fmt_num(value)}.dp)")
        else:
            lines.append(f"    val {key} = RoundedCornerShape({fmt_num(value)}.dp)")
    lines.append("}")
    return "\n".join(lines) + "\n"


def pascal(name):
    return name[0].upper() + name[1:]


def gen_kotlin_color(tokens):
    scheme = tokens["colorScheme"]
    lines = [kt_header("import androidx.compose.ui.graphics.Color\n")]
    lines.append("// ── M3 baseline 配色（colorScheme.light/dark）──────────────────────────────────")
    lines.append("// 注：ErrorLight 已按 SSOT 修正为 M3 标准 #B3261E（旧值 0xB32610 有 alpha=00 透明 bug）。")
    for mode, suffix in (("light", "Light"), ("dark", "Dark")):
        lines.append("")
        for key, hexv in scheme[mode].items():
            lines.append(f"val {pascal(key)}{suffix} = {kotlin_color(hexv)}")
    lines += ["", "// ── 功能色（color 组，不随主题切换）。引用方式：MaterialTheme.appColors.focusRing ──────────"]
    color_group = {k: v for k, v in tokens["color"].items() if not k.startswith("_")}
    # 顶层 val 命名历史约定：vibrant* 无 Color 后缀，其余有
    top_names = {}
    for key, hexv in color_group.items():
        top = pascal(key) if key.startswith("vibrant") else pascal(key) + "Color"
        top_names[key] = top
        lines.append(f"val {top} = {kotlin_color(hexv)}")
    lines += ["", "/** 功能色集合，通过 [MaterialTheme.appColors] 访问。 */", "object AppColors {"]
    for key in color_group:
        lines.append(f"    val {key} = {top_names[key]}")
    lines.append("}")
    return "\n".join(lines) + "\n"


def gen_kotlin_typography(tokens):
    typo = {k: v for k, v in tokens["typography"].items() if not k.startswith("_")}
    lines = [kt_header("import androidx.compose.material3.Typography\nimport androidx.compose.ui.text.TextStyle\n"
                       "import androidx.compose.ui.text.font.FontFamily\nimport androidx.compose.ui.text.font.FontWeight\n"
                       "import androidx.compose.ui.unit.sp\n"),
             "/** M3 baseline 字号阶梯（15 role 全量显式声明，防御 M3 库默认值变更）。 */",
             "val Typography = Typography("]
    roles = list(typo.items())
    for i, (role, spec) in enumerate(roles):
        sep = "," if i < len(roles) - 1 else ""
        lines.append(f"    {role} = TextStyle(")
        lines.append("        fontFamily = FontFamily.Default,")
        lines.append(f"        fontWeight = {KOTLIN_WEIGHTS[spec['weight']]},")
        lines.append(f"        fontSize = {fmt_num(spec['size'])}.sp,")
        lines.append(f"        lineHeight = {fmt_num(spec['lineHeight'])}.sp,")
        lines.append(f"        letterSpacing = {fmt_num(spec['letterSpacing'])}.sp")
        lines.append(f"    ){sep}")
    lines.append(")")
    return "\n".join(lines) + "\n"


def kotlin_prop_line(group, name, kind, value):
    if kind == "size":
        return f"    val {name} = {fmt_num(value)}.dp"
    if kind == "int":
        return f"    val {name} = {fmt_num(value)}"
    if kind == "ms":
        return f"    val {name} = {fmt_num(value)}"
    if kind == "float":
        return f"    val {name} = {fmt_num(value)}f"
    if kind == "color":
        return f"    val {name} = {kotlin_color(value)}"
    if kind == "weight":
        return f"    val {name} = {KOTLIN_WEIGHTS[value]}"
    if kind == "array":
        items = gradient_kotlin(value)
        body = ", ".join(items)
        return f"    val {name}: List<Color> = listOf({body})"
    raise ValueError(f"未知 kind: {kind}")


def gen_kotlin_tokens(tokens):
    lines = [kt_header("import androidx.compose.ui.graphics.Color\nimport androidx.compose.ui.text.font.FontWeight\n"
                       "import androidx.compose.ui.unit.dp\n"),
             "/**",
             " * 组件级 token 镜像（与 iOS DesignTokens.swift 同源生成）。",
             " * 页面代码引用这些 object，禁止内联硬编码 dp/hex（漂移扫描见 DESIGN_TOKENS_SPEC.md §4）。",
             " */"]
    for group in ANDROID_TOKENS_ORDER:
        data = tokens[group]
        comment = data.get("_comment")
        lines.append("")
        if comment:
            lines.append(f"/** {comment} */")
        lines.append(f"object {ENUM_NAMES[group]} {{")
        if group == "motion":
            for k, v in data["durationMs"].items():
                lines.append(f"    val {k}Ms = {fmt_num(v)}")
            lines.append(f"    val staggerMs = {fmt_num(data['staggerMs'])}")
            lines.append(f"    val searchDebounceMs = {fmt_num(data['searchDebounceMs'])}")
            lines.append(f"    val shutterDebounceMs = {fmt_num(data['shutterDebounceMs'])}")
            gp = data["galleryPreview"]
            lines.append(f"    val galleryPreviewFadeMs = {fmt_num(gp['fadeMs'])}")
            lines.append(f"    val galleryPreviewScaleMs = {fmt_num(gp['scaleMs'])}")
            lines.append(f"    val galleryPreviewScaleFrom = {fmt_num(gp['scaleFrom'])}f")
            lines.append(f"    val galleryPreviewScaleTo = {fmt_num(gp['scaleTo'])}f")
        else:
            for name, kind, value in flatten(group, data):
                lines.append(kotlin_prop_line(group, name, kind, value))
        lines.append("}")
    return "\n".join(lines) + "\n"


# ── Ardot apply_variables payload ─────────────────────────────────────────────

def ardot_color(hex_str):
    r, g, b, a = parse_hex(hex_str)
    return {"r": round(r, 4), "g": round(g, 4), "b": round(b, 4), "a": round(a, 4)}


def ardot_float_scopes(var_name):
    """FLOAT 变量全名（group/name）→ scopes（无歧义键发窄域，其余 None=不发、保持全域可绑）。

    sync-ardot-variables.py --check 按同一规则比对画布侧 scopes，改这里必须同步那边。
    """
    if "strokeWidth" in var_name:
        return ["STROKE_FLOAT"]
    if var_name.startswith("radius/") or "Radius" in var_name or "radius" in var_name:
        return ["CORNER_RADIUS"]
    return None


def gen_ardot_payload(tokens):
    """输出 apply_variables 入参：单变量集 'PoLang Tokens'。

    模式顺序 ["Dark", "Light"]：Ardot 侧既有集合（2026-08-14 Figma 先导期创建）唯一模式
    就叫 Dark，apply_variables 会把 "Mode 1" 重命名为 modes[0]，必须保持 Dark 在前，
    否则会把存量深色值错标为 Light。语义色命名沿用既有 `scheme/<key>` 前缀（勿改，避免双份漂移）。

    scopes 规约（2026-08-19 双向化）：COLOR 一律 ALL_FILLS；FLOAT 中 strokeWidth 类 →
    STROKE_FLOAT、radius 类 → CORNER_RADIUS（见 ardot_float_scopes），其余 FLOAT/STRING
    不发 scopes 字段（Ardot 默认全域可绑）。
    """
    variables = {}
    for key, hexv in tokens["colorScheme"]["light"].items():
        variables[f"scheme/{key}"] = {
            "type": "COLOR",
            "valuesByMode": {
                "Dark": ardot_color(tokens["colorScheme"]["dark"][key]),
                "Light": ardot_color(hexv),
            },
            "scopes": ["ALL_FILLS"],
        }
    for group in ("color", "statusColor"):
        for key, hexv in tokens[group].items():
            if key.startswith("_"):
                continue
            variables[f"{group}/{key}"] = {"type": "COLOR", "value": ardot_color(hexv), "scopes": ["ALL_FILLS"]}
    for group, data in tokens.items():
        if group.startswith("_") or group in ("color", "statusColor", "colorScheme", "typography"):
            continue
        for name, kind, value in flatten(group, data):
            if kind in ("size", "int", "ms", "float"):
                full_name = f"{group}/{name}"
                entry = {"type": "FLOAT", "value": value}
                scopes = ardot_float_scopes(full_name)
                if scopes:
                    entry["scopes"] = scopes
                variables[full_name] = entry
            elif kind == "color":
                variables[f"{group}/{name}"] = {"type": "COLOR", "value": ardot_color(value), "scopes": ["ALL_FILLS"]}
            elif kind == "weight":
                variables[f"{group}/{name}"] = {"type": "STRING", "value": value}
    for role, spec in tokens["typography"].items():
        if role.startswith("_"):
            continue
        for field in ("size", "lineHeight", "letterSpacing"):
            variables[f"typography/{role}/{field}"] = {"type": "FLOAT", "value": spec[field]}
        variables[f"typography/{role}/weight"] = {"type": "STRING", "value": spec["weight"]}
    return {"PoLang Tokens": {"modes": ["Dark", "Light"], "variables": variables}}


# ── 主流程 ────────────────────────────────────────────────────────────────────

def collect_outputs(tokens):
    return {
        IOS_OUT: gen_swift(tokens),
        ANDROID_DS / "Spacing.kt": gen_kotlin_spacing(tokens),
        ANDROID_DS / "AppShapes.kt": gen_kotlin_shapes(tokens),
        ANDROID_DS / "Color.kt": gen_kotlin_color(tokens),
        ANDROID_DS / "Typography.kt": gen_kotlin_typography(tokens),
        ANDROID_DS / "DesignTokens.kt": gen_kotlin_tokens(tokens),
        ARDOT_OUT: json.dumps(gen_ardot_payload(tokens), ensure_ascii=False, indent=2) + "\n",
    }


def main():
    check_mode = "--check" in sys.argv
    tokens = json.loads(JSON_PATH.read_text(encoding="utf-8"))
    outputs = collect_outputs(tokens)

    if check_mode:
        stale = []
        for path, content in outputs.items():
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                stale.append(path)
        if stale:
            print("❌ 生成物与 design-tokens.json 不一致（禁止手改生成物；改 JSON 后重跑生成器）：")
            for path in stale:
                print(f"   - {path.relative_to(PROJECT_ROOT)}")
                if path.exists():
                    diff = difflib.unified_diff(
                        path.read_text(encoding="utf-8").splitlines(),
                        outputs[path].splitlines(),
                        fromfile="磁盘", tofile="重新生成", lineterm="")
                    print("\n".join(list(diff)[:40]))
            sys.exit(1)
        print(f"✅ design-tokens 生成物与 SSOT 一致（{len(outputs)} 个文件）")
        return

    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"写入 {path.relative_to(PROJECT_ROOT)}")
    print("完成。iOS/Android 镜像 + Ardot payload 已同步。")


if __name__ == "__main__":
    main()
